SolarFS2c/SolarFS2c/urls.py
from __future__ import unicode_literals

from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin

from mezzanine.core.views import direct_to_template
from mezzanine.conf import settings
admin.autodiscover()

from classic.views import *

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

urlpatterns = i18n_patterns("",
    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    ("^admin/", include(admin.site.urls)),
)

if settings.USE_MODELTRANSLATION:
    urlpatterns += patterns('',
        url('^i18n/$', 'django.views.i18n.set_language', name='set_language'),
    )

urlpatterns += patterns('',
    # We don't want to presume how your homepage works, so here are a
    # few patterns you can use to set it up.

    # HOMEPAGE AS STATIC TEMPLATE
    # ---------------------------
    # This pattern simply loads the index.html template. It isn't
    # commented out like the others, so it's the default. You only need
    # one homepage pattern, so if you use a different one, comment this
    # one out.
    #url("^home/$", direct_to_template, {"template": "index.html"}, name="home"),
    #url("^index/$", direct_to_template, {"template": "index.html"}, name="home"),

    url("^solarfs-form/$", SolarFSform, name="SolarFSform"),
        
    # Direct to mezzanine home page. 
    url("^mezzanine/$", direct_to_template, {"template": "index-mez.html"}, name="mezzanine"),
    # Accepts a country code, e.g., "/en/"
    #url("^[A-Za-z]{2}/mezzanine/$", direct_to_template, {"template": "index-mez.html"}, name="home"),
    #url("^/$", direct_to_template, {"template": "index.html"}, name="home"),

    url("^$", home_page, name="home"), # Make home page editable.
        
    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part.
    # Also note that the normal rule of adding a custom
    # template per page with the template name using the page's slug
    # doesn't apply here, since we can't have a template called
    # "/.html" - so for this case, the template "pages/index.html"
    # should be used if you want to customize the homepage's template.
    url("^$", "mezzanine.pages.views.page", {"slug": "/"}, name="home"),
    #url("^$", "mezzanine.pages.views.page", {"slug": "/"}, name="index"),

    # HOMEPAGE FOR A BLOG-ONLY SITE
    # -----------------------------
    # This pattern points the homepage to the blog post listing page,
    # and is useful for sites that are primarily blogs. If you use this
    # pattern, you'll also need to set BLOG_SLUG = "" in your
    # ``settings.py`` module, and delete the blog page object from the
    # page tree in the admin if it was installed.

    # url("^$", "mezzanine.blog.views.blog_post_list", name="home"),

    # MEZZANINE'S URLS
    # ----------------
    # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
    # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
    # WILL NEVER BE MATCHED!

    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.
    ("^", include("mezzanine.urls")),

    # MOUNTING MEZZANINE UNDER A PREFIX
    # ---------------------------------
    # You can also mount all of Mezzanine's urlpatterns under a
    # URL prefix if desired. When doing this, you need to define the
    # ``SITE_PREFIX`` setting, which will contain the prefix. Eg:
    # SITE_PREFIX = "my/site/prefix"
    # For convenience, and to avoid repeating the prefix, use the
    # commented out pattern below (commenting out the one above of course)
    # which will make use of the ``SITE_PREFIX`` setting. Make sure to
    # add the import ``from django.conf import settings`` to the top
    # of this file as well.
    # Note that for any of the various homepage patterns above, you'll
    # need to use the ``SITE_PREFIX`` setting as well.

    # ("^%s/" % settings.SITE_PREFIX, include("mezzanine.urls"))

)

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

SolarFS2c/classic/models.py
from django.db import models
from django.contrib import admin

#Python imports
from django.template.defaultfilters import slugify
import datetime 

# Import python settings, and defintion from app.
from SolarFS2c.settings import MEDIA_ROOT
from classic import SfsLight

# Geocoders
import pygeocoder, geocoder
# Pandas et al.
import pandas, pvlib
from pvlib.location import Location 
# Matplotlib routinesl.
import matplotlib
matplotlib.use('Agg') # Must have here - not after from matplotlib.~ commands. 
#from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.backends.backend_agg import FigureCanvasAgg
from matplotlib.figure import Figure
from matplotlib import pyplot

# Create your models here.

class MyProfile(models.Model):
    user = models.OneToOneField("auth.User")
    #date_of_birth = models.DateField()
    bio = models.TextField()

class Calculation(models.Model):
    # Geocode variables. 
    address = models.TextField(max_length=120, blank=True, null=True, verbose_name='Address')
    address_slug = models.SlugField(max_length=120, blank=True, null=True)
    formatted_address = models.TextField(max_length=120, null=True, blank=True)
    coordinates = models.CharField(max_length=80, blank=True, null=True, verbose_name='latitude, longitude')
    #elevation = models.CharField(max_length=60, blank=True, null=True, verbose_name='Elevation (AMSL)', default="None'")
    elevation = models.FloatField(default=0.0, blank=True, null=True)
    # Panda variables. 
    #begin = models.CharField(max_length=30, default='2015, 7, 1, 11', blank=True, null=True)
    #begin = models.DateField(max_length=30, null=True)
    begin = models.CharField(max_length=30, blank=True, null=True)
    end = models.CharField(max_length=30, default='2015, 7, 1, 12', blank=True, null=True)
    frequency = models.CharField(max_length=20, default='3Min', blank=True, null=True)
    time_sequence = models.TextField(max_length=600, null=True, blank=True)
    # pvlib variables. 
    ephem_sequence = models.TextField(max_length=6000, null=True, blank=True)
    statistics = models.TextField(max_length=300, null=True, blank=True)
    irradiance_sequence = models.TextField(max_length=6000, null=True, blank=True)
    # Solar panel specs.  
    panel_azimuth = models.FloatField(max_length=20, default=180, blank=True, null=True, verbose_name='Panel azimuth (degrees from north)')
    panel_tilt = models.FloatField(max_length=20, default=30, blank=True, null=True, verbose_name='Panel tilt (degrees from vertical)')
    doc =  models.CharField(max_length=80, blank=True, null=True)
    pix1 =  models.CharField(max_length=80, blank=True, null=True)
    pix2 =  models.CharField(max_length=80, blank=True, null=True)

    # Creates a slug name. 
    prepopulated_fields = {
                           "address_slug": ("address",),
    }
    
    def __str__(self):
        return self.address
        #return '%s %s' % (self.question, self.answer)

    # Gets latitude & longitude from address. 
    def address2llh(self, address):
        geoAddress = pygeocoder.Geocoder.geocode(self.address)
        self.formatted_address = geoAddress.formatted_address
        self.coordinates = geoAddress.coordinates

        # Use geocoder to get elevation in meters AMSL. 
        elevation = self.address2elev(self.address)
        self.elevation = elevation
        # pyemphem requires a numeric elevation value. 
        return Location(*geoAddress.coordinates, altitude = elevation, name = self.address)
        
    # geocoder gets elevation from address. (g.location) returns lat, long 
    def address2elev(self, address):
        g = geocoder.elevation(address)
        elevation = g.elevation
        if elevation is None:    
            elevation = 0    
        return elevation
    
    def ephemeris(self, begin, end, frequency):
        location = self.address2llh(self.address)

        # Invoke panda routine.
        strBegin = begin.split(',')
        intBegin = [int(x) for x in strBegin]
        strEnd = end.split(',')
        intEnd = [int(x) for x in strEnd]

        # Avoids the "..." ellipsis that appear in data. 
        pandas.set_option('display.max_rows', 1000000)
    
        timeSequence = pandas.date_range(
            start=datetime.datetime(intBegin[0], intBegin[1], intBegin[2], intBegin[3]), 
            end=datetime.datetime(intEnd[0], intEnd[1], intEnd[2], intEnd[3]), freq = frequency)
        #self.time_sequence = timeSequence

        ##################
        # Solar ephemeris.
        # # # # # # # # # # # # # 
        ephemSequence = pvlib.solarposition.pyephem(
            timeSequence, location).drop(
                ['apparent_elevation', 'apparent_azimuth', 
                'apparent_zenith', 'elevation'], axis=1)
        self.ephem_sequence = ephemSequence
        # Create plot figure file. 
        ephemSequence.plot()
        pix1_name = 'ephem_' + self.address_slug + '.png' 
        plot_path = MEDIA_ROOT + 'plots/' + pix1_name
        pyplot.savefig(plot_path)
        ##################

        # Solar ephemeris. 
        eph_seq = str(ephemSequence)
        eph_seq_lines = eph_seq.split('\n')
        self.time_sequence = eph_seq_lines

        # Compute statistics. 
        self.statistics  = ephemSequence.describe()

        ##################
        # Solar specifications.
        # # # # # # # # # # # # # 
        location = self.address2llh(self.address)
        solarZenith = ephemSequence['zenith']
        solarAzi = ephemSequence['azimuth']
        irradianceSequence = pvlib.clearsky.ineichen(timeSequence, location)
        
        DNI = irradianceSequence['dni']
        DB = SfsLight.directBeam(self.panel_tilt, solarZenith, self.panel_azimuth-solarAzi, DNI)  

        irradianceSequence['DB'] = DB
        self.irradiance_sequence = irradianceSequence

        irradianceSequence.plot()
        pix2_name = 'irrad_' + self.address_slug + '.png' 
        plot_path = MEDIA_ROOT + 'plots/' + pix2_name
        pyplot.savefig(plot_path)
        ##################

        # Create plot figure file. 
        '''ephemSequence.plot()
        plot_path = MEDIA_ROOT + 'plots/ephemSequence.png'
        pyplot.savefig(plot_path)'''

        return

    # Write data to file, that can be downloaded. 
    def write_data(self):
        doc_name = 'SolarFS_' + self.address_slug + '.dat' 
        self.doc = doc_name
        pix1_name = 'ephem_' + self.address_slug + '.png' 
        self.pix1 = pix1_name
        pix2_name = 'irrad_' + self.address_slug + '.png' 
        self.pix2 = pix2_name
        data_path = MEDIA_ROOT + 'docs/' + doc_name
        f = open(data_path,"w")
        f.write('Formatted address: %s\n' % self.formatted_address)
        f.write('Coordinates (latitude, longitude): %s\n' % str(self.coordinates))
        f.write('Elevation: (meters AMSL) %s\t(feet): %f\n\n' % ( str(self.elevation), self.elevation/0.3048 ))
        #### Pandas time sequence ####
        f.write('Time sequence:\n')
        f.write('Start: %s\n' % self.begin)
        f.write('Stop: %s\n' % self.end)
        f.write('Frequency: %s\n\n' % self.frequency)
        #### #### ####
        f.write('Ephemeris:\n %s\n\n' % self.ephem_sequence)
        f.write('Statistics:\n %s\n\n' % self.statistics)
        f.write('Irradiance:\n %s\n\n' % self.irradiance_sequence)
        f.close()
        return
    
    def save(self, *args, **kwargs):
        # Create slugs of title, Country, and State_or_Provincea thumbnail name of avatar. 
        self.address_slug = slugify(self.address)
        # Invoke 'address2llh' function. . 
        self.formatted_address = self.address2llh(self.address)
        # Solar calculations.
        self.ephemeris(self.begin, self.end, self.frequency)
        # Write data to file. 
        self.write_data()
        # Save all. 
        super(Calculation, self).save()

class CalculationAdmin(admin.ModelAdmin):
    search_fields = ["address"]
    display_fields = ["address"]
    # Creates a slug name within ~/admin/. 
    prepopulated_fields = {
                           "address_slug": ("address",), 
}

SolarFS2c/classic/templates/classic/pages/base-altered.html
<!doctype html>
<html lang="{{ LANGUAGE_CODE }}"{% if LANGUAGE_BIDI %} dir="rtl"{% endif %}>
  {% load pages_tags mezzanine_tags i18n staticfiles %}

  <head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="{% block meta_keywords %}{% endblock %}">
    <meta name="description" content="{% block meta_description %}{% endblock %}">
    <title>{% block meta_title %}{% endblock %}{% if settings.SITE_TITLE %} | {{ settings.SITE_TITLE }}{% endif %}</title>
    <link rel="shortcut icon" href="{% static "img/favicon.ico" %}">

    {% ifinstalled mezzanine.blog %}
      <link rel="alternate" type="application/rss+xml" title="RSS" href="{% url "blog_post_feed" "rss" %}">
      <link rel="alternate" type="application/atom+xml" title="Atom" href="{% url "blog_post_feed" "atom" %}">
    {% endifinstalled %}

    {% compress css %}
      <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
      <link rel="stylesheet" href="{% static "css/mezzanine.css" %}">
      <link rel="stylesheet" href="{% static "css/bootstrap-theme.css" %}">

			{# ## Added ## #}
			<link rel="stylesheet" href="{% static "css/codehilite.css" %}">
			<link rel="stylesheet" href="{% static "css/custom.css" %}">
			<link rel="stylesheet" href="{% static "css/SFS.css" %}">
		
			<link rel="stylesheet" href="{% static "css/jquery-ui.css" %}"> 
			<link rel="stylesheet" href="{% static "css/jquery-ui.min.css" %}"> 
			<link rel="stylesheet" href="{% static "css/jquery-ui.structure.css" %}"> 
			<link rel="stylesheet" href="{% static "css/jquery-ui.structure.min.css" %}"> 
			<link rel="stylesheet" href="{% static "css/jquery-ui.theme.css" %}"> 
			<link rel="stylesheet" href="{% static "css/jquery-ui.theme.min.css" %}"> 
			<link rel="stylesheet" href="{% static "css/jquery-ui.slider.css" %}"> 
			<link rel="stylesheet" href="{% static "css/jquery-ui-timepicker-addon.css" %}">
			<link rel="stylesheet" href="{% static "css/jquery.simple-dtpicker.css" %}">
		
		
			<!------ Alternative ------>
			<link rel="stylesheet" href="{% static "codehilite.css" %}">
			<link rel="stylesheet" href="{% static "custom.css" %}">
			<link rel="stylesheet" href="{% static "SFS.css" %}">
		
			<link rel="stylesheet" href="{% static "jquery-ui.css" %}"> 
			<link rel="stylesheet" href="{% static "jquery-ui.min.css" %}"> 
			<link rel="stylesheet" href="{% static "jquery-ui.structure.css" %}"> 
			<link rel="stylesheet" href="{% static "jquery-ui.structure.min.css" %}"> 
			<link rel="stylesheet" href="{% static "jquery-ui.theme.css" %}"> 
			<link rel="stylesheet" href="{% static "jquery-ui.theme.min.css" %}"> 
			<link rel="stylesheet" href="{% static "jquery-ui.slider.css" %}"> 
			<link rel="stylesheet" href="{% static "jquery-ui-timepicker-addon.css" %}">
			<link rel="stylesheet" href="{% static "jquery.simple-dtpicker.css" %}">
			<!------------------------------>
			<!-- javascript flot formatting file -->
			<link rel="stylesheet" type="text/css" href="{% static "css/flot.css" %}">
			<link rel="stylesheet" type="text/css" href="{% static "flot.css" %}">
		
			<link rel="stylesheet" type="text/css" href="/static/css/flot.css">
		
			{# ######### #}

      {% if LANGUAGE_BIDI %}
          <link rel="stylesheet" href="{% static "css/bootstrap-rtl.css" %}">
      {% endif %}
      {% ifinstalled cartridge.shop %}
          <link rel="stylesheet" href="{% static "css/cartridge.css" %}">
          {% if LANGUAGE_BIDI %}
              <link rel="stylesheet" href="{% static "css/cartridge.rtl.css" %}">
          {% endif %}
      {% endifinstalled %}
      {% block extra_css %}{% endblock %}
    {% endcompress %}

    {% compress js %}
      {# <script src="{% static "mezzanine/js/"|add:settings.JQUERY_FILENAME %}"></script> #}
			<script src="{% static 'mezzanine/js/jquery-1.7.2.min.js' %}"></script>
      <script src="{% static "js/bootstrap.js" %}"></script>
      <script src="{% static "js/bootstrap-extras.js" %}"></script>

			{# #### javascript flot files. #### #}
			<!--[if lte IE 8]><script type="text/javascript" language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.2/excanvas.min.js"></script><![endif]-->
		
			<script type="text/javascript" language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.2/jquery.flot.js"></script>
		
			{# <script type="text/javascript" language="javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script> #}
			<script type="text/javascript" language="javascript" src="https://code.jquery.com/jquery-2.0.3.min.js"></script>
			<script type="text/javascript" language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.2/jquery.flot.min.js"></script>
		
			<script type="text/javascript" src="{% static "js/jquery.js" %}"></script>
			<script type="text/javascript" src="{% static "js/jquery.flot.js" %}"></script>
			<script type="text/javascript" src="{% static "js/jquery.flot.time.js" %}"></script>
			<script type="text/javascript" src="{% static "js/jquery.flot.symbol.js" %}"></script>
			<script type="text/javascript" src="{% static "js/jquery.flot.axislabels.js" %}"></script>
			<script type="text/javascript" src="{% static "js/hashtable.js" %}"></script>
		
			<script type="text/javascript" src="{% static "js/jquery-ui.js" %}"></script> 
			<script type="text/javascript" src="{% static "jquery-ui.js" %}"></script> 
			<script type="text/javascript" src="{% static "js/jquery-min.js" %}"></script> 
			<script type="text/javascript" src="{% static "jquery-min.js" %}"></script> 
			<script type="text/javascript" src="{% static "js/jquery-ui-min.js" %}"></script> 
			<script type="text/javascript" src="{% static "jquery-ui-min.js" %}"></script> 
		
			<script type="text/javascript" src="{% static "js/jquery-ui-sliderAccess.js" %}"></script> 
			<script type="text/javascript" src="{% static "jquery-ui-sliderAccess.js" %}"></script> 
			<script type="text/javascript" src="{% static "js/jquery-ui-timepicker-addon.js" %}"></script> 
			<script type="text/javascript" src="{% static "jquery-ui-timepicker-addon.js" %}"></script>
 
			<!-- Include the jquery Ui here. -->
			<!-- This formatted the CalculationForm "begin" and "end" widget fields. -->
			<!--<script>
			/*$(function() {
				$( ".datetimepicker" ).datetimepicker({
					changeMonth: true,
					changeYear: true,
					//yearRange: "1900:2012",
					yearRange: "1995:2018",
					// You can put more options here.
					dateFormat: "yy, mm, dd,",
					timeFormat: "HH, mm" //HH for 0-24 hour range.
					//dateFormat: "yyyy/mm/dd"
				});
			});*/
			</script>-->
			<!-- Date picker jquery script. Must use #id_name instead of #name! -->
	    <script>
		    $.datepicker.setDefaults({
	        changeMonth: true,
	        changeYear: true,
					yearRange: "1995:2018",
				});
				$(function() {
					$( "#id_begin" ).datetimepicker({
						dateFormat: "yy, mm, dd,",
						timeFormat: "HH, mm", //HH for 0-24 hour range.
						// Select minimum date for "end" field. Won't work for time. 
						onClose: function( selectedDateTime ) { 
							$( "#id_end" ).datetimepicker( "option", "minDate", selectedDateTime );
						}
					});
				});
		    $(function() {
					$( "#id_end" ).datetimepicker({
						dateFormat: "yy, mm, dd,",
						timeFormat: "HH, mm",  //HH for 0-24 hour range.
					});
		    });
	    </script>
	
			<script type="text/javascript" language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.2/jquery.flot.symbol.js"></script>
			<script type="text/javascript" language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/flot/0.8.2/jquery.flot.axislabels.js"></script>
			{# ###################### #}

      {% block extra_js %}{% endblock %}
    {% endcompress %}

    <!--[if lt IE 9]>
        <script src="{% static "js/html5shiv.js" %}"></script>
        <script src="{% static "js/respond.min.js" %}"></script>
    <![endif]-->

    {% block extra_head %}{% endblock %}
  </head>

  <body id="{% block body_id %}body{% endblock %}">

	  <div class="navbar navbar-default navbar-fixed-top" role="navigation">
			<br>
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">{% trans "Toggle Navigation" %}</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          {# {% if settings.SITE_TITLE %}<a class="navbar-brand" href="/">{{ settings.SITE_TITLE }}</a>{% endif %} #}
          {# {% if settings.SITE_TAGLINE %}<p class="navbar-text visible-lg">{{ settings.SITE_TAGLINE }}</p>{% endif %} #}
        </div>
        <div class="navbar-collapse collapse">
          {% search_form "all" %}
          {% page_menu "pages/menus/dropdown.html" %}
        </div>
      </div>
    </div>

		<!-- ------------------------------------- -->
		<!-- Top banner, containing image. -->
		<!-- - - - - - - - - - - - - - - - - - - - - - -->
		<table class='headerTable'>
		  <tr>
		    <td class='cell_spacer'></td>
		  </tr>
		  <tr>
		    <!--
		    <td><img src='{% static 'images/TronaPinnacles.jpg' %}' width=100%></td>
		    <td><img src='{% static 'images/TronaPinnacles-Finnish_AF_F-18C_RIAT_t.jpg' %}' width=100%></td>
		    -->
		    <td><img src='{% static 'images/1200px-Hetch_Hetchy_Reservoir.jpg' %}' width=100%></td>
		  </tr>
		</table>
		<!-- ------------------------------------- -->
	    
    <div class="container">

	    <div class="col-md-9 left">
		    {% nevercache %}
	        {% if messages %}
	          <div class="messages">
	            {% for message in messages %}
	              <div class="alert alert-dismissable alert-{{ message.tags }}" data-alert="alert">
	                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	                {{ message }}
	              </div>
	            {% endfor %}
	          </div>
	        {% endif %}
		    {% endnevercache %}

		    <ul class="breadcrumb">
			    {% spaceless %}
		        {% block breadcrumb_menu %}{% page_menu "pages/menus/breadcrumb.html" %}{% endblock %}
			    {% endspaceless %}
		    </ul>

		    {% block title %}{% endblock %}

	    </div>

	    <div class="col-md-3 right">
	      {% nevercache %}
	        {% include "includes/language_selector.html" %}
	        {% include "includes/user_panel.html" %}
	      {% endnevercache %}
	    </div>

    </div>

    <div class="container">
      <div class="row">

				<!-- ------------------------------------- -->
				<!-- Middle column. -->
				<!-- - - - - - - - - - - - - - - - - - - - - - -->
        <div class="col-md-11 middle">
          {% block main %}{% endblock %}
        </div>
				<!-- ------------------------------------- -->
			
				<!-- ------------------------------------- -->
				<!-- Right column - two white panels. -->
				<!-- - - - - - - - - - - - - - - - - - - - - - -->
        <!--<div class="col-md-3 right">
          {% nevercache %}
            {% include "includes/language_selector.html" %}
            {% include "includes/user_panel.html" %}
          {% endnevercache %}
          
          <div class="panel panel-default">
            <div class="panel-body">
              {% block right_panel %}
                {% ifinstalled mezzanine.twitter %}
                  {% include "twitter/tweets.html" %}
                {% endifinstalled %}
              {% endblock %}
            </div>
          </div>

        </div>-->
				<!-- ------------------------------------- -->

      </div>
    </div>

    <footer>
      <div class="container">
				<!-- Comment out footer menu. -->
        <!-- {% page_menu "pages/menus/footer.html" %} -->
        <div class="row">
          <p class="site-info text-center">
            {% trans "Powered by" %}
            <a href="http://mezzanine.jupo.org">Mezzanine</a>{% ifinstalled cartridge.shop %},
            <a href="http://cartridge.jupo.org">Cartridge</a>{% endifinstalled %}
            {% trans "and" %}
            <a href="http://www.djangoproject.com">Django</a>
            <span class="separator">|</span>
            {% trans "Theme by" %} <a target="_blank" href="http://getbootstrap.com">Bootstrap</a>
            {% ifinstalled mezzanine.mobile %}
              <span class="separator">|</span>
              <a href="{% url "set_device" "mobile" %}?next={{ request.path }}">{% trans "View Mobile Site" %}</a>
            {% endifinstalled %}
          </p>
        </div>
      </div>
    </footer>

    {% include "includes/footer_scripts-altered.html" %}

  </body>
</html>

SolarFS2c/classic/templates/classic/pages/page.html
{% extends "base.html" %}
{% load mezzanine_tags keyword_tags %}

{% block meta_title %}{{ page.meta_title }}{% endblock %}

{% block meta_keywords %}{% metablock %}
{% keywords_for page as keywords %}
{% for keyword in keywords %}
    {% if not forloop.first %}, {% endif %}
    {{ keyword }}
{% endfor %}
{% endmetablock %}{% endblock %}

{% block meta_description %}{% metablock %}
{{ page.description }}
{% endmetablock %}{% endblock %}

{% block title %}
{% editable page.title %}{{ page.title }}{% endeditable %}
{% endblock %}

{% block main %}
{% endblock %}

SolarFS2c/classic/templates/classic/pages/richtextpage.html
{# {% extends "pages/page.html" %} #}
{% extends "base-photos.html" %}

{% load mezzanine_tags %}

{% block main %}{{ block.super }}

	{% editable page.richtextpage.content %}
		{{ page.richtextpage.content|richtext_filters|safe }}
	{% endeditable %}

{% endblock %}